### ISSUE TITLE
Is there any license?

### ISSUE THREAD

**Issue by h6ah4i** [bydavy/android-number-morphing#1]
Hello.

Thank you for developing a great library. I'm considering to use this library in my app. However, I was not able to find any license texts of this library. Is it published under MIT license same as the android-parallax-example?

Thanks,
h6ah4i

**Comment by bydavy** [comment]
You are right I totally forgot it. I just fixed it. Thanks again. 

https://github.com/bydavy/android-number-morphing/commit/e755111a8086402b9f47425ae0f4b0c3ed7bed44
